Feature/twig
mediamonks/pota pull request #95
Opened 2022-11-17 15:41 UTC by ThaNarie

Adds twig support to the muban-scripts and muban-template.

2023-01-18 15:35 UTC, leroykorterink requested changes

2023-01-18 15:35 UTC, leroykorterink commented on support/twig-server/package.json
> +    "dev": "nodemon --ext ts --exec 'tsm' example/esm/index.ts",
I think `ts-node-dev` is a lot quicker compared to `nodemon`, both work fine 🤷🏻

2023-01-18 15:35 UTC, leroykorterink commented on templates/muban/config/twig/helpers/toAttributeString.cjs
> +    .map(([key, value]) => `${prefix + kebabCase(key)}="${value}"`)
```ts
.map(([key, value]) => `${prefix}${kebabCase(key)}="${value}"`)
```

2023-04-04 08:04 UTC, larsvanbraam approved these changes

2023-04-14 12:04 UTC, merged